project_id = "pimmztrboudsdyxdqiav"

[functions.government-schemes]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.analyze-crop]
verify_jwt = false

[functions.market-prices]
verify_jwt = false
